version: '3.8'

services:
  app:
    image: alramz/alramz-crm:latest
    container_name: alramz-crm-app
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      APP_ENV: local
      APP_KEY: base64:daMAophjWaXQJSGFLXHbVb40sVKdzfR+EwxvFL709LM=
      APP_DEBUG: "true"
      APP_URL: http://localhost

      LOG_CHANNEL: stack

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: alramz_crm
      DB_USERNAME: root
      DB_PASSWORD: rootsecret

      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120

    depends_on:
      db:
        condition: service_healthy

    command: >
      sh -c "php artisan migrate --force && php-fpm"

    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache


  db:
    image: mysql:8.0
    container_name: alramz-crm-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: alramz_crm
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./alramz_crm.sql:/docker-entrypoint-initdb.d/alramz_crm.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootsecret"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  db_data:










